// src/lib/components/portfolio/ProjectCard.svelte
<script lang="ts">
	import { marked } from '$lib/utils';
	import Badge from '../ui/badge/badge.svelte';

	let _class = '';
	export { _class as class };
	export let title: string;
	export let href: string = '';
	export let description: string;
	export let dates: string;
	export let tags: readonly string[];
	export let link: string = '';
	export let image: string = '';
	export let video: string = '';
	export let links: { icon: any; type: string; href: string }[] = [];
</script>

<!-- Card -->
<div
	class="relative flex h-full flex-col overflow-hidden rounded-lg border bg-card text-card-foreground transition-all duration-300 ease-out hover:shadow-lg"
>
	{#if video || image}
		<a href={href || '#'} target="_blank" rel="noopener noreferrer" class="block cursor-pointer">
			{#if video}
				<video
					class="pointer-events-none mx-auto h-32 w-full object-cover object-top sm:h-40"
					src={video}
					autoplay
					loop
					muted
				></video>
			{:else if image}
				<img
					class="h-32 w-full overflow-hidden object-cover object-top sm:h-40"
					src={image}
					alt={title}
				/>
			{/if}
		</a>
	{/if}
	<!-- Card Header -->
	<div class="flex flex-col px-2" class:pt-4={!video && !image}>
		<div class="space-y-1">
			<!-- Card Title -->
			<div class="mt-1 text-base">{title}</div>
			<time class="font-sans text-xs">{dates}</time>
			<div class="hidden font-sans text-xs underline print:visible">
				{link?.replace('https://', '').replace('www.', '').replace('/', '')}
			</div>
			<div
				class="prose max-w-full text-pretty font-sans text-xs text-muted-foreground dark:prose-invert"
			>
				{@html marked(description)}
			</div>
		</div>
	</div>
	<!-- Card Content -->
	<div class="mt-auto flex flex-col text-pretty px-2 font-sans text-sm text-muted-foreground">
		{#if tags && tags.length > 0}
			<div class="mt-2 flex flex-wrap gap-1">
				{#each tags as tag}
					<Badge class="rounded-[4px] px-1 py-0 text-[10px]" variant="secondary">
						{tag}
					</Badge>
				{/each}
			</div>
		{/if}
	</div>
	<!-- Card Footer -->
	<div class="flex items-center px-2 pb-2 pt-2">
		{#if links && links.length > 0}
			<div class="flex flex-row flex-wrap items-start gap-1">
				{#each links as link}
					<a href={link?.href} target="_blank" rel="noopener noreferrer">
						<Badge class="flex items-center justify-center gap-1 px-2 py-1 text-[10px]">
							<!-- {link.icon} -->
							<svelte:component this={link.icon} class="mb-px size-3" strokeWidth={1.6} />
							{link.type}
						</Badge>
					</a>
				{/each}
			</div>
		{/if}
	</div>
</div>

// src/app/components/projects/ProjectCard.tsx
"use client";

import Link from "next/link";
import { memo } from "react";
import { Badge, Button, H3, MonoText, P } from "@/components/ui";
import { ExternalLink, Github, Star } from "@/components/ui/icons";
import { useLanguage } from "@/lib/language-store";
import type { Project } from "@/types/portfolio";

interface ProjectCardProps {
  project: Project;
}

export const ProjectCard = memo(({ project }: ProjectCardProps) => {
  const { t } = useLanguage();
  const linkLabels = t.projects.links;

  return (
    <div className="group/card relative flex h-full flex-col">
      {/* Header: title + date */}
      <div className="flex flex-col gap-1.5 sm:flex-row sm:items-start sm:justify-between sm:gap-3">
        <H3 className="text-sm sm:text-base break-words pr-0 sm:pr-2 flex items-start gap-2 transition-colors duration-200 ease-[cubic-bezier(0.25,1,0.5,1)] group-hover/card:text-accent">
          {project.featured && (
            <Star
              className="mt-px shrink-0 size-3 sm:size-3.5 text-accent opacity-95 animate-pulse hover:animate-none transition-all duration-150"
              aria-hidden="true"
            />
          )}
          {project.title}
        </H3>
        {project.dates && (
          <MonoText className="shrink-0 whitespace-nowrap tabular-nums text-[10px] sm:text-xs text-muted-foreground">
            {project.dates}
          </MonoText>
        )}
      </div>

      {/* Description + tech tags */}
      <div className="mt-3 flex-1 sm:mt-4">
        <P className="text-xs sm:text-sm leading-relaxed text-muted-foreground">
          {project.description}
        </P>

        <div className="mt-3 flex flex-wrap gap-1 sm:mt-4 sm:gap-1.5">
          {project.technologies.map((tech, index) => (
            <Badge
              key={tech}
              className="text-[10px] sm:text-xs transition-all duration-200 ease-[cubic-bezier(0.25,1,0.5,1)] motion-reduce:transition-none hover:border-accent/60 hover:bg-accent/25 hover:text-accent hover:shadow-md hover:shadow-accent/5 variant-projects"
              style={{ transitionDelay: `${index * 20}ms` }}
            >
              {tech}
            </Badge>
          ))}
        </div>
      </div>

      {/* Links */}
      {project.links && (
        <div className="mt-4 flex flex-wrap gap-2 border-t border-dashed border-border/60 pt-4 sm:mt-5">
          {project.links.github && (
            <Button asChild variant="outline" size="sm">
              <Link
                href={project.links.github}
                target="_blank"
                rel="noopener noreferrer"
                className="group/link text-xs sm:text-sm"
              >
                <Github
                  className="mr-1.5 size-3 sm:mr-2 sm:size-3.5 icon-hover-rotate group-hover/link:scale-110"
                  aria-hidden="true"
                />
                {linkLabels.code}
              </Link>
            </Button>
          )}
          {project.links.demo && (
            <Button asChild variant="outline" size="sm">
              <Link
                href={project.links.demo}
                target="_blank"
                rel="noopener noreferrer"
                className="group/link text-xs sm:text-sm"
              >
                <ExternalLink
                  className="mr-1.5 size-3 sm:mr-2 sm:size-3.5 icon-hover-rotate group-hover/link:scale-110"
                  aria-hidden="true"
                />
                {linkLabels.demo}
              </Link>
            </Button>
          )}
          {project.links.website && (
            <Button asChild variant="outline" size="sm">
              <Link
                href={project.links.website}
                target="_blank"
                rel="noopener noreferrer"
                className="group/link text-xs sm:text-sm"
              >
                <ExternalLink
                  className="mr-1.5 size-3 sm:mr-2 sm:size-3.5 icon-hover-rotate group-hover/link:scale-110"
                  aria-hidden="true"
                />
                {linkLabels.website}
              </Link>
            </Button>
          )}
        </div>
      )}
    </div>
  );
});

ProjectCard.displayName = "ProjectCard";
