// src/app/components/ProjectCard.tsx
"use client";

import { ExternalLink, Github } from "lucide-react";
import Link from "next/link";
import type { Project } from "@/types/portfolio";

interface ProjectCardProps {
  project: Project;
}

export const ProjectCard = ({ project }: ProjectCardProps) => {
  return (
    <article className="group rounded-lg border border-border bg-card p-4 sm:p-6 transition-all hover:border-foreground">
      {/* Header */}
      <div className="mb-4 flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
        <h3 className="text-base sm:text-lg font-semibold text-foreground pr-2">
          {project.title}
        </h3>
        {project.dates && (
          <span className="font-mono text-xs text-muted-foreground whitespace-nowrap">
            {project.dates}
          </span>
        )}
      </div>

      {/* Description */}
      <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
        {project.description}
      </p>

      {/* Technologies */}
      <div className="mb-4 flex flex-wrap gap-2">
        {project.technologies.slice(0, 6).map((tech) => (
          <span
            key={tech}
            className="rounded border border-border bg-muted px-2 py-0.5 font-mono text-xs text-muted-foreground"
          >
            {tech}
          </span>
        ))}
        {project.technologies.length > 6 && (
          <span className="rounded border border-border bg-muted px-2 py-0.5 font-mono text-xs text-muted-foreground">
            +{project.technologies.length - 6}
          </span>
        )}
      </div>

      {/* Links */}
      {project.links && (
        <div className="flex flex-wrap gap-3">
          {project.links.github && (
            <Link
              href={project.links.github}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-xs sm:text-sm text-muted-foreground transition-colors hover:text-foreground"
            >
              <Github className="h-4 w-4" />
              <span>Code</span>
            </Link>
          )}
          {project.links.demo && (
            <Link
              href={project.links.demo}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-xs sm:text-sm text-muted-foreground transition-colors hover:text-foreground"
            >
              <ExternalLink className="h-4 w-4" />
              <span>Demo</span>
            </Link>
          )}
          {project.links.website && (
            <Link
              href={project.links.website}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-xs sm:text-sm text-muted-foreground transition-colors hover:text-foreground"
            >
              <ExternalLink className="h-4 w-4" />
              <span>Website</span>
            </Link>
          )}
        </div>
      )}
    </article>
  );
};

// src/lib/components/portfolio/ProjectCard.svelte
<script lang="ts">
	import { marked } from '$lib/utils';
	import Badge from '../ui/badge/badge.svelte';

	let _class = '';
	export { _class as class };
	export let title: string;
	export let href: string = '';
	export let description: string;
	export let dates: string;
	export let tags: readonly string[];
	export let link: string = '';
	export let image: string = '';
	export let video: string = '';
	export let links: { icon: any; type: string; href: string }[] = [];
</script>

<!-- Card -->
<div
	class="flex h-full flex-col overflow-hidden border transition-all duration-300 ease-out hover:shadow-lg rounded-lg bg-card text-card-foreground"
>
	{#if video || image}
		<a href={href || '#'} target="_blank" rel="noopener noreferrer" class="block cursor-pointer">
			{#if video}
				<video
					class="pointer-events-none mx-auto h-32 sm:h-40 w-full object-cover object-top"
					src={video}
					autoplay
					loop
					muted
				></video>
			{:else if image}
				<img class="h-32 sm:h-40 w-full overflow-hidden object-cover object-top" src={image} alt={title} />
			{/if}
		</a>
	{/if}
	<!-- Card Header -->
	<div class="px-2 flex flex-col" class:pt-4={!video && !image}>
		<div class="space-y-1">
			<!-- Card Title -->
			<div class="mt-1 text-base">{title}</div>
			<time class="font-sans text-xs">{dates}</time>
			<div class="hidden font-sans text-xs underline print:visible">
				{link?.replace('https://', '').replace('www.', '').replace('/', '')}
			</div>
			<div
				class="prose dark:prose-invert max-w-full text-pretty font-sans text-xs text-muted-foreground"
			>
				{@html marked(description)}
			</div>
		</div>
	</div>
	<!-- Card Content -->
	<div class="mt-auto flex flex-col px-2 text-pretty font-sans text-sm text-muted-foreground">
		{#if tags && tags.length > 0}
			<div class="mt-2 flex flex-wrap gap-1">
				{#each tags as tag}
					<Badge class="rounded-[4px] px-1 py-0 text-[10px]" variant="secondary">
						{tag}
					</Badge>
				{/each}
			</div>
		{/if}
	</div>
	<!-- Card Footer -->
	<div class="px-2 pb-2 flex items-center pt-2">
		{#if links && links.length > 0}
			<div class="flex flex-row flex-wrap items-start gap-1">
				{#each links as link}
					<a href={link?.href} target="_blank" rel="noopener noreferrer">
						<Badge class="flex gap-1 px-2 py-1 text-[10px] items-center justify-center">
							<!-- {link.icon} -->
							<svelte:component this={link.icon} class="size-3 mb-px" strokeWidth={1.6} />
							{link.type}
						</Badge>
					</a>
				{/each}
			</div>
		{/if}
	</div>
</div>
